# Generated by Django 5.2.3 on 2025-06-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_employeecheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complainant_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complainant Name'),
        ),
    ]
